version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: finance_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: finance_pass
      POSTGRES_DB: finance_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U finance_user -d finance_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: finance_api
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://finance_user:finance_pass@db:5432/finance_db
      JWT_SECRET: lab7-super-secret-key-2026
      JWT_EXPIRE_SECONDS: 3600
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: